### ISSUE TITLE
Configuration for rule "sort-sequence-values" is invalid: Value [] should NOT have fewer than 1 items

### ISSUE THREAD

**Issue by stefanvacareanu7** [ota-meshi/eslint-plugin-yml#194]
Hello there,

When I am trying to integrate your plugin with codacy-eslint, I get the following error:

```
Docker exited with code 1
stdout: 
stderr: Error: BaseConfig:
        Configuration for rule "yml/sort-sequence-values" is invalid:
        Value [] should NOT have fewer than 1 items.

    at ConfigValidator.validateRuleOptions (/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2027:23)
    at /node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2082:18
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateRules (/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2079:34)
    at ConfigValidator.validateConfigArray (/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2205:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3963:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3769:21)
    at FileEnumerator._iterateFilesWithFile (/node_modules/eslint/lib/cli-engine/file-enumerator.js:368:43)
    at FileEnumerator._iterateFiles (/node_modules/eslint/lib/cli-engine/file-enumerator.js:349:25)
    at FileEnumerator.iterateFiles (/node_modules/eslint/lib/cli-engine/file-enumerator.js:299:59)
    at iterateFiles.next (<anonymous>)
    at CLIEngine.executeOnFiles (/node_modules/eslint/lib/cli-engine/cli-engine.js:786:48)
    at ESLint.lintFiles (/node_modules/eslint/lib/eslint/eslint.js:550:23)
    at /dist/src/engineImpl.js:34:44
    at Generator.next (<anonymous>)
    at fulfilled (/dist/src/engineImpl.js:5:58)
           
Stacktrace:
com.codacy.plugins.runners.BinaryDockerRunner.$anonfun$run$4(BinaryDockerRunner.scala:87)
scala.util.Success.flatMap(Try.scala:251)
com.codacy.plugins.runners.BinaryDockerRunner.run(BinaryDockerRunner.scala:72)
com.codacy.plugins.results.traits.ToolRunner.$anonfun$apply$2(ToolRunner.scala:77)
com.codacy.plugins.results.traits.CodacyDocker$.$anonfun$usingDockerConfig$2(CodacyDocker.scala:45)
com.codacy.plugins.utils.FileHelper$.$anonfun$usingNewFile$2(FileHelper.scala:51)
scala.util.Try$.apply(Try.scala:213)
com.codacy.plugins.utils.FileHelper$.usingNewFile(FileHelper.scala:45)
com.codacy.plugins.results.traits.CodacyDocker$.usingConfigPath(CodacyDocker.scala:57)
com.codacy.plugins.results.traits.CodacyDocker$.$anonfun$usingDockerConfig$1(CodacyDocker.scala:39)
scala.Option.map(Option.scala:230)
com.codacy.plugins.results.traits.CodacyDocker$.usingDockerConfig(CodacyDocker.scala:38)
com.codacy.plugins.results.traits.ToolRunner.$anonfun$apply$1(ToolRunner.scala:76)
scala.util.Try$.apply(Try.scala:213)
com.codacy.plugins.results.traits.ToolRunner.apply(ToolRunner.scala:61)
com.codacy.plugins.results.traits.ToolRunner.run(ToolRunner.scala:49)
codacy.plugins.test.multiple.MultipleTests$.runTool(MultipleTests.scala:90)
codacy.plugins.test.multiple.MultipleTests$.$anonfun$run$1(MultipleTests.scala:46)
scala.collection.parallel.AugmentedIterableIterator.map2combiner(RemainsIterator.scala:116)
scala.collection.parallel.AugmentedIterableIterator.map2combiner$(RemainsIterator.scala:113)
scala.collection.parallel.immutable.ParVector$ParVectorIterator.map2combiner(ParVector.scala:66)
scala.collection.parallel.ParIterableLike$Map.leaf(ParIterableLike.scala:1056)
scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
scala.collection.parallel.ParIterableLike$Map.tryLeaf(ParIterableLike.scala:1053)
scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:170)
scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:157)
scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:150)
scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

Do you know what could be the cause and how I could fix it?

Please let me know if I should provide more information.

Best,
Stefan

**Comment by ota-meshi** [comment]
You need to set your preferred order and the point at which the order applies to the rule in your configuration.

https://ota-meshi.github.io/eslint-plugin-yml/rules/sort-sequence-values.html
